name: Deploy Production Bot
on: [push]
env:
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
    deploy-via-sftp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - id: SFTPDeploy
              uses: Creepios/sftp-action@v1.0.3
              with:
                username: root
                host: ß${{ secrets.SSH_HOST }}
                port: 22
                privateKey:  ${{ secrets.SSH_PRIVATE_KEY }}
                localPath: '.'
                remotePath: /testCopy
