name: Update Discord Bot
run-name: ${{ github.actor }} is updating the production discord bot
on:
    push:
        branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Bot
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
            username: root
            server: ${{ secrets.SSH_HOST }}
            port: 22
            ssh_private_key:  ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: ./*
            remote_path: /
