name: Update Discord Bot
run-name: ${{ github.actor }} is updating the production discord bot
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Bot
        uses: Creepios/sftp-action@v1.0.3
        with:
            username: root
            host: ${{ secrets.SSH_HOST }}
            port: 22
            privateKey:  ${{ secrets.SSH_PRIVATE_KEY }}
            localPath: '.'
            remotePath: /

